name: "godot-ci export"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GODOT_VERSION: 4.6
  EXPORT_NAME: project-steam-frame-tomorrow
  PROJECT_PATH: .

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux
    
  export-android-debug:
    name: Android Debug Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.6

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Android build template
        run: |
          if [ ! -d "android/build" ]; then
            echo "Installing Android build template..."

            mkdir -p android
            echo "${GODOT_VERSION}.stable" > android/.build_version

            unzip -o /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable/android_source.zip -d android/build
          fi

      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Android Debug Build
        run: |
          mkdir -v -p build/android
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "Android Debug" "$EXPORT_DIR/android/$EXPORT_NAME-debug.apk"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug
          path: build/android
    
  export-android:
    name: Android Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.6

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Android build template
        run: |
          if [ ! -d "android/build" ]; then
            echo "Installing Android build template..."

            mkdir -p android
            echo "${GODOT_VERSION}.stable" > android/.build_version

            unzip -o /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable/android_source.zip -d android/build
          fi

      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Decode keystore
        run: |
          echo "${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > /root/release.keystore

      - name: Android Build
        run: |
          mkdir -v -p build/android
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH

          # Inject signing config
          sed 's@keystore/release=".*"@keystore/release="/root/release.keystore"@g' -i export_presets.cfg
          sed 's@keystore/release_user=".*"@keystore/release_user="${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}"@g' -i export_presets.cfg
          sed 's@keystore/release_password=".*"@keystore/release_password="${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD }}"@g' -i export_presets.cfg

          godot --headless --verbose --export-release "Android" "$EXPORT_DIR/android/$EXPORT_NAME.apk"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/android

  export-mac:
    name: Mac Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/$EXPORT_NAME.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: build/mac

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [export-windows, export-linux, export-mac, export-android]

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Get latest tag
        id: tag
        run: |
          git fetch --tags
          latest=$(git tag -l "v*" --sort=-v:refname | head -n 1)

          if [ -z "$latest" ]; then
            next="v1"
          else
            num=${latest#v}
            next="v$((num + 1))"
          fi

          echo "tag=$next" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git tag ${{ steps.tag.outputs.tag }} || exit 0
          git push origin ${{ steps.tag.outputs.tag }} || exit 0

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          files: |
            windows/**
            linux/**
            mac/**
            android/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}